version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-restaurant-manager
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=${DB_USERNAME:-danielguerra}
      - DB_PASSWORD=${DB_PASSWORD:-postgres}
      - DB_NAME=${DB_NAME:-business_app}
      - PORT=3001
      - JWT_SECRET=${JWT_SECRET:-supersecret_access}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN:-15m}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET:-supersecret_refresh}
      - JWT_REFRESH_EXPIRES_IN=${JWT_REFRESH_EXPIRES_IN:-7d}
      - HOST_FRONTEND=${HOST_FRONTEND:-http://localhost:3000}
      - NODE_ENV=development
      - API_KEY=${API_KEY}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_USER=${MAIL_USER}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_FROM=${MAIL_FROM:-no-reply@api-resthub.com}
    depends_on:
      db:
        condition: service_started
    networks:
      - app-network

  db:
    image: postgres:15-alpine
    container_name: restaurant_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USERNAME:-danielguerra}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-business_app}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
